color0 #0a2133
color1 #fd4663
color2 #67ade4
color3 #545cde
color4 #9154de
color5 #93c5ec
color6 #9499ea
color7 #f2f2f3
color8 #5f6b74
color9 #fd4663
color10 #67ade4
color11 #545cde
color12 #9154de
color13 #93c5ec
color14 #9499ea
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0a2133
background            #0a2133
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #0d2c44
active_border_color   #67ade4
inactive_border_color #0d2c44
url_color             #67ade4
