color0 #dcdcef
color1 #fd4663
color2 #1d1b97
color3 #5b248e
color4 #852d84
color5 #191782
color6 #4e1b7e
color7 #18181b
color8 #7a78af
color9 #fd4663
color10 #1d1b97
color11 #5b248e
color12 #852d84
color13 #191782
color14 #4e1b7e
color15 #18181b

cursor                #18181b
cursor_text_color     #dcdcef
background            #dcdcef
foreground            #18181b
selection_foreground  #47474f
selection_background  #b3b2dc
active_border_color   #1d1b97
inactive_border_color #b3b2dc
url_color             #1d1b97
