color0 #111318
color1 #ffb4ab
color2 #ddbce0
color3 #bec6dc
color4 #abc7ff
color5 #ddbce0
color6 #bec6dc
color7 #e2e2e9
color8 #8e9099
color9 #ffb4ab
color10 #ddbce0
color11 #bec6dc
color12 #abc7ff
color13 #ddbce0
color14 #bec6dc
color15 #e2e2e9

cursor                #e2e2e9
cursor_text_color     #111318
background            #111318
foreground            #e2e2e9
selection_foreground  #c4c6d0
selection_background  #44474e
url_color             #abc7ff